<div class="contentMentionslLegales">
    <div class="contentMentionslLegales__introduction">
        <section class="contentMentionslLegales__introduction__sectionIntro">
            <h2 class="contentMentionslLegales__introduction__sectionIntro__h2">Mentions Légales</h2>
        </section>
    </div>
    <div class="contentMentionslLegales__content">
        <section class="contentMentionslLegales__content__sectionImpaire">
            <h2 class="contentMentionslLegales__content__sectionImpaire__h2">1. Présentation du site</h2>
            <p class="contentMentionslLegales__content__sectionImpaire__p">En vertu de l’article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l’économie numérique, il est précisé aux utilisateurs du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a> l’identité des différents intervenants dans le cadre de sa réalisation et de son suivi :</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Propriétaire : Dominique Quaintenne Rochefort le vieil - 32 Ter rue de Bretagne 53810 Changé </p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Contact du propriétaire : dominique.quaintenne@gmail.com</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Hébergeur : à préciser</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Contact de l'hébergeur : à préciser</p>
        </section>
        <section class="contentMentionslLegales__content__sectionPaire">
            <h2 class="contentMentionslLegales__content__sectionPaire__h2">2. Conditions générales d’utilisation du site et des services proposés.</h2>
            <p class="contentMentionslLegales__content__sectionPaire__p">L’utilisation du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a> implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a> sont donc invités à les consulter de manière régulière.</p>
            <p class="contentMentionslLegales__content__sectionPaire__p">Ce site est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par Dominique Quaintenne, qui s’efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l’intervention.</p>
            <p class="contentMentionslLegales__content__sectionPaire__p">Le site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a> est mis à jour régulièrement par Dominique Quaintenne. De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s’imposent néanmoins à l’utilisateur qui est invité à s’y référer le plus souvent possible afin d’en prendre connaissance.</p>
        </section>
        <section class="contentMentionslLegales__content__sectionImpaire">
            <h2 class="contentMentionslLegales__content__sectionImpaire__h2"><span class="contentMentionslLegales__content__sectionImpaire__h2__span">3. </span>Limitations contractuelles sur les données techniques.</h2>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Le site utilise les technologies JavaScript et PHP.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Ce site n'utilise pas de bases de données et ne stocke aucune données.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Le site Internet ne pourra être tenu responsable de dommages matériels liés à l’utilisation du site. De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour.</p>
        </section>
        <section class="contentMentionslLegales__content__sectionPaire">
            <h2 class="contentMentionslLegales__content__sectionPaire__h2"><span class="contentMentionslLegales__content__sectionPaire__h2__span">4. </span>Propriété intellectuelle et contrefaçons</h2>
            <p class="contentMentionslLegales__content__sectionPaire__p">Dominique Quaintenne est propriétaire des droits de propriété intellectuelle ou détient les droits d’usage sur tous les éléments accessibles sur le site, notamment les textes, images, graphismes, logo, icônes, sons, logiciels.</p>
            <p class="contentMentionslLegales__content__sectionPaire__p">Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de : Dominique Quaintenne.</p>
            <p class="contentMentionslLegales__content__sectionPaire__p">Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</p>
        </section>
        <section class="contentMentionslLegales__content__sectionImpaire">
            <h2 class="contentMentionslLegales__content__sectionImpaire__h2"><span class="contentMentionslLegales__content__sectionImpaire__h2__span">5. </span>Limitations de responsabilité.</h2>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Dominique Quaintenne ne pourra être tenu responsable des dommages directs et indirects causés au matériel de l’utilisateur, lors de l’accès au site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionImpaire__p__a">DQuaintenne.fr</a>, et résultant soit de l’utilisation d’un matériel ne répondant pas aux spécifications indiquées au point 4, soit de l’apparition d’un bug ou d’une incompatibilité.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Dominique Quaintenne ne pourra également être tenue responsable des dommages indirects (tels par exemple qu’une perte de marché ou perte d’une chance) consécutifs à l’utilisation du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionImpaire__p__a">DQuaintenne.fr</a>.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Des espaces interactifs (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs. Dominique Quaintenne se réserve le droit de supprimer, sans mise en demeure préalable, tout contenu déposé dans cet espace qui contreviendrait à la législation applicable en France, en particulier aux dispositions relatives à la protection des données. Le cas échéant, Dominique Quaintenne se réserve également la possibilité de mettre en cause la responsabilité civile et/ou pénale de l’utilisateur, notamment en cas de message à caractère raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilisé (texte, photographie…).</p>
        </section>
        <section class="contentMentionslLegales__content__sectionPaire">
            <h2 class="contentMentionslLegales__content__sectionPaire__h2"><span class="contentMentionslLegales__content__sectionPaire__h2__span">6. </span>Gestion des données personnelles.</h2>
            <p class="contentMentionslLegales__content__sectionPaire__p">En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l’article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995.</p>
            <p class="contentMentionslLegales__content__sectionPaire__p">A l’occasion de l’utilisation du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a>, peuvent êtres recueillies : l’URL des liens par l’intermédiaire desquels l’utilisateur a accédé au site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a>, le fournisseur d’accès de l’utilisateur, l’adresse de protocole Internet (IP) de l’utilisateur.</p>
            <p class="contentMentionslLegales__content__sectionPaire__p">En tout état de cause Dominique Quaintenne ne collecte des informations personnelles relatives à l’utilisateur que pour le besoin de certains services proposés par le site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a>. L’utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu’il procède par lui-même à leur saisie. Il est alors précisé à l’utilisateur du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a> l’obligation ou non de fournir ces informations.</p>
            <p class="contentMentionslLegales__content__sectionPaire__p">Conformément aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, tout utilisateur dispose d’un droit d’accès, de rectification et d’opposition aux données personnelles le concernant, en effectuant sa demande écrite et signée, accompagnée d’une copie du titre d’identité avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse doit être envoyée.</p>
            <p class="contentMentionslLegales__content__sectionPaire__p">Aucune information personnelle de l’utilisateur du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a> n’est publiée à l’insu de l’utilisateur, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers. Seule l’hypothèse du rachat de Dominique Quaintenne et de ses droits permettrait la transmission des dites informations à l’éventuel acquéreur qui serait à son tour tenu de la même obligation de conservation et de modification des données vis à vis de l’utilisateur du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a></p>
        </section>
        <section class="contentMentionslLegales__content__sectionImpaire">
            <h2 class="contentMentionslLegales__content__sectionImpaire__h2"><span class="contentMentionslLegales__content__sectionImpaire__h2__span">7. </span>Liens hypertextes et cookies.</h2>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Le site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionImpaire__p__a">DQuaintenne.fr</a> contient un certain nombre de liens hypertextes vers d’autres sites, mis en place avec l’autorisation de Dominique Quaintenne. Cependant, Dominique Quaintenne n’a pas la possibilité de vérifier le contenu des sites ainsi visités, et n’assumera en conséquence aucune responsabilité de ce fait.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">La navigation sur le site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionImpaire__p__a">DQuaintenne.fr</a> est susceptible de provoquer l’installation de cookie(s) sur l’ordinateur de l’utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas l’identification de l’utilisateur, mais qui enregistre des informations relatives à la navigation d’un ordinateur sur un site. Les données ainsi obtenues visent à faciliter la navigation ultérieure sur le site, et ont également vocation à permettre diverses mesures de fréquentation.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Le refus d’installation d’un cookie peut entraîner l’impossibilité d’accéder à certains services. <span style="font-weight: bold;">L’utilisateur peut toutefois configurer son ordinateur de la manière suivante, pour refuser l’installation des cookies :</span></p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Sous Edge : onglet outil (pictogramme representant 3 points horizontaux en haut a droite), puis paramètres (pictogramme en forme de rouage de la colonne qui vient de s'ouvrir) puis cliquer sur le cadenas (situé entre le rouage et la clef) et qui représente la catégorie Confidentialité et sécurité. Dans la rubrique Cookies de la colonne sélectionner Bloquer tous les cookies.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Sous Firefox : en haut de la fenêtre du navigateur, cliquez sur le bouton Firefox, puis aller dans l’onglet Options. Cliquer sur l’onglet Vie privée. Paramétrez les Règles de conservation sur : utiliser les paramètres personnalisés pour l’historique. Enfin décochez-la pour désactiver les cookies.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Sous Safari : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par un rouage). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section “Confidentialité”, cliquez sur Paramètres de contenu. Dans la section “Cookies”, vous pouvez bloquer les cookies.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Sous Chrome : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par trois lignes horizontales). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section “Confidentialité”, cliquez sur préférences. Dans l’onglet “Confidentialité”, vous pouvez bloquer les cookies.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">En vertu de l’article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l’économie numérique, il est précisé aux utilisateurs du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionImpaire__p__a">DQuaintenne.fr </a> l’identité des différents intervenants dans le cadre de sa réalisation et de son suivi :</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Le site n’est pas déclaré à la CNIL car il n’exploite pas les données personnelles comme indiqué sur <a href="https://www.cnil.fr/fr/rgpd-de-quoi-parle-t-on" class="contentMentionslLegales__content__sectionImpaire__p__a">cette page</a></p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.</p>
        </section>
        <section class="contentMentionslLegales__content__sectionPaire">
            <h2 class="contentMentionslLegales__content__sectionPaire__h2"><span class="contentMentionslLegales__content__sectionPaire__h2__span">8. </span>Droit applicable et attribution de juridiction.</h2>
            <p class="contentMentionslLegales__content__sectionPaire__p">Tout litige en relation avec l’utilisation du site <a href="http://dquaintenne.fr/accueil" class="contentMentionslLegales__content__sectionPaire__p__a">DQuaintenne.fr</a> est soumis au droit français. Il est fait attribution exclusive de juridiction aux tribunaux compétents de Paris.</p>
        </section>
        <section class="contentMentionslLegales__content__sectionImpaire">
            <h2 class="contentMentionslLegales__content__sectionImpaire__h2"><span class="contentMentionslLegales__content__sectionImpaire__h2__span">9. </span>Les principales lois concernées.</h2>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Loi n° 78-17 du 6 janvier 1978, notamment modifiée par la loi n° 2004-801 du 6 août 2004 relative à l’informatique, aux fichiers et aux libertés.</p>
            <p class="contentMentionslLegales__content__sectionImpaire__p">Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l’économie numérique.</p>
        </section>
        <section class="contentMentionslLegales__content__sectionPaire">
            <h2 class="contentMentionslLegales__content__sectionPaire__h2"><span class="contentMentionslLegales__content__sectionPaire__h2__span">10. </span>Lexique</h2>
            <p class="contentMentionslLegales__content__sectionPaire__p">Utilisateur : Internaute se connectant, utilisant le site susnommé.</p>
            <p class="contentMentionslLegales__content__sectionPaire__p">Informations personnelles : « les informations qui permettent, sous quelque forme que ce soit, directement ou non, l’identification des personnes physiques auxquelles elles s’appliquent » (article 4 de la loi n° 78-17 du 6 janvier 1978).</p>
        </section>
    </div>  
    <script>styleMentionsLegales();</script>
</div>

        